package model;

public enum EventCommandName implements CommandName {
    EVENT_STARTED,
    SETUP_COMPLETE,
    END_EVENT,
    PLAYER_END_EVENT,
    EVENT_COMPLETED,
    FIND_CARD_INTERACTIVE_OR_NOT,
    EVENT_INTERACTIVE,
    EVENT_NON_INTERACTIVE,
    EVENT_SHIELD_LOST,
    EVENT_SHIELD_GAIN
}
