package model;

public enum GameStatus {
    READY,
    STARTED,
    RUNNING,
    TAKING_TURN,
    FINDING_QUEST_SPONSOR,
    PROMPTING_QUEST_SPONSOR,
    FINDING_QUEST_PARTICIPANTS,
    PROMPTING_QUEST_PARTICIPANT,
    RUNNING_QUEST,
    TAKING_QUEST_TURN,
    ENDING_QUEST_TURN,
    RUNNING_EVENT
}
