package model;

public enum GameCommandName implements CommandName {
    READY,
    IS_READY,
    UNREADY,
    IS_UNREADY,
    GET_ATTACHED_PLAYER,
    RETURN_ATTACHED_PLAYER,
    GAME_STARTED,
    PLAYER_TURN,
    NOT_PLAYER_TURN,
    TAKE_TURN,
    END_TURN,
    ENDED_TURN,
    TOOK_TURN,
    DISCARD_CARD,
    DISCARDED_CARD,
    GAME_COMPLETE,
    COMPLETE_GAME,
    COMPLETED_GAME
}
